### ISSUE TITLE
Address out of range error with Flipper when using IR folder examples

### ISSUE THREAD

**Issue by Zagrophyte** [Spexivus/csv2ir#1]
I'm testing out the `ir` folder from the repo on my Flipper and encountered an issue where many do not load anything in the UI for the Flipper, and generate an error in debug logging (see below).

These files (any many more) cause this issue, on at least the NEC/Panasonic protocols:
https://github.com/Spexivus/csv2ir/blob/main/ir/2wire/Unknown_2wire.ir
https://github.com/Spexivus/csv2ir/blob/main/ir/Panasonic/TV1.ir

After troubleshooting a bit with one of the Flipper maintainers on the discord, the address on the first 2wire example was determined to likely be NEC Extended (NECext), not regular NEC. There appears to be 4 different NEC protocols that are supported by the flipper, but this isn't being specified in the converted IR files. (See: [https://github.com/flipperdevices/flipperzero-firmware/blob/dev/lib/infrared/encoder_decoder/nec/infrared_nec_spec.c](https://github.com/flipperdevices/flipperzero-firmware/blob/dev/lib/infrared/encoder_decoder/nec/infrared_nec_spec.c)

Here is an output for the first [IR file](https://github.com/Spexivus/csv2ir/blob/main/ir/2wire/Unknown_2wire.ir) that was tested:
`36931 [E][InfraredParser]: Address is out of range (mask 0x000000FF): 0x2020`

However, could the following item be related? I noticed in the python script that the Device and Sub-device are checked but then Device is used twice (row1 row1) in the output? [https://github.com/Spexivus/csv2ir/blob/6d701c0873003a865740a77fbce1ccd621cfb565/csv2ir.py#L67](https://github.com/Spexivus/csv2ir/blob/6d701c0873003a865740a77fbce1ccd621cfb565/csv2ir.py#L67)

**Comment by Spexivus** [comment]
Could you confirm if this is now working properly for you?

**Comment by Zagrophyte** [comment]
I re-ran the CSVs I had in the folder and it just makes a single partial file now, did anything in the format change?:
![image](https://user-images.githubusercontent.com/6778687/164951286-a19a9539-384c-4ad7-809c-2171c92c869c.png)
![image](https://user-images.githubusercontent.com/6778687/164951353-7d6cc95e-9a9d-45b4-9610-f9b47954eb27.png)
![image](https://user-images.githubusercontent.com/6778687/164951260-2adb4836-8c67-42ab-8ee2-ac4edae551af.png)
![image](https://user-images.githubusercontent.com/6778687/164951264-3d2a6cca-82d4-485b-940f-2c5a5de17843.png)

**Comment by Zagrophyte** [comment]
Output on test files (see attached) when customProtocol NOT set:
[32,159.csv](https://github.com/Spexivus/csv2ir/files/8558780/32.159.csv)
[128,0.csv](https://github.com/Spexivus/csv2ir/files/8558781/128.0.csv)

```D:\Repos\csv2ir>python3 csv2ir.py
Place .csv files in the (C:\Users\trose\Desktop\csv2ir\csv) directory. Should I open it for you? (y/n).


Press enter when you are finished placing files.

Would you like to set a custom protocol? (y/n)


Converting files...
Traceback (most recent call last):
  File "csv2ir.py", line 94, in <module>
    main()
  File "csv2ir.py", line 55, in main
    if customProtocol == False:
UnboundLocalError: local variable 'customProtocol' referenced before assignment
```

When customProtocol IS set, output is as follows:
```D:\Repos\csv2ir>python3 csv2ir.py
Place .csv files in the (C:\Users\trose\Desktop\csv2ir\csv) directory. Should I open it for you? (y/n).
n

Press enter when you are finished placing files.

Would you like to set a custom protocol? (y/n)
y

Enter the protocol you would like to use
Currently supported protocols: NEC, NECext, Samsung32).
NECext

Converting files...
Traceback (most recent call last):
  File "csv2ir.py", line 94, in <module>
    main()
  File "csv2ir.py", line 88, in main
    print(f"\nConverted {counter} files in {finish-start} seconds ({counter/(finish-start)} files per second)")
ZeroDivisionError: float division by zero
```

Additionally, files have 2nd byte group malformed:
![image](https://user-images.githubusercontent.com/6778687/165196416-7d037eca-2fba-4212-8160-f42669b841bc.png)
